import type { PlantComponent } from "../types/PlantComponent";

export const mockComponents: PlantComponent[] = [
  {
    id: "conveyor-main",
    name: "Main Conveyor Belt",
    type: "segment",
    status: "on",
    online: true,
    lastChanged: new Date().toISOString(),
    stats: { cycles: 1240, uptimeHours: 312 },
  },
  {
    id: "station-input",
    name: "Input Station",
    type: "station",
    status: "on",
    online: true,
    lastChanged: new Date().toISOString(),
    stats: { cycles: 980, uptimeHours: 310 },
  },
  {
    id: "conveyor-short-1",
    name: "Short Conveyor 1",
    type: "segment",
    status: "on",
    online: true,
    lastChanged: new Date().toISOString(),
    stats: { cycles: 1100, uptimeHours: 300 },
  },
  {
    id: "sensor-rfid-1",
    name: "RFID Sensor 1",
    type: "sensor",
    status: "on",
    online: true,
    lastChanged: new Date().toISOString(),
    stats: { cycles: 4500, uptimeHours: 312 },
  },
  {
    id: "lift-1",
    name: "Lift Unit",
    type: "actuator",
    status: "off",
    online: true,
    lastChanged: new Date().toISOString(),
    stats: { cycles: 620, uptimeHours: 200 },
  },
  {
    id: "storage-rack",
    name: "High-Bay Storage",
    type: "station",
    status: "on",
    online: true,
    lastChanged: new Date().toISOString(),
    stats: { cycles: 410, uptimeHours: 290 },
  },
  {
    id: "conveyor-long-1",
    name: "Long Conveyor 1",
    type: "segment",
    status: "on",
    online: false,
    lastChanged: new Date().toISOString(),
    stats: { cycles: 890, uptimeHours: 250 },
  },
  {
    id: "sensor-optical-1",
    name: "Optical Sensor 1",
    type: "sensor",
    status: "on",
    online: true,
    lastChanged: new Date().toISOString(),
    stats: { cycles: 5200, uptimeHours: 312 },
  },
  {
    id: "station-output",
    name: "Output Station",
    type: "station",
    status: "on",
    online: true,
    lastChanged: new Date().toISOString(),
    stats: { cycles: 970, uptimeHours: 310 },
  },
  {
    id: "fill-unit",
    name: "Pneumatic Fill Unit",
    type: "actuator",
    status: "off",
    online: true,
    lastChanged: new Date().toISOString(),
    stats: { cycles: 340, uptimeHours: 180 },
  },
  {
    id: "sensor-inductive-1",
    name: "Inductive Sensor 1",
    type: "sensor",
    status: "on",
    online: true,
    lastChanged: new Date().toISOString(),
    stats: { cycles: 3800, uptimeHours: 305 },
  },
  {
    id: "conveyor-rotate-1",
    name: "Rotating Conveyor 1",
    type: "actuator",
    status: "on",
    online: true,
    lastChanged: new Date().toISOString(),
    stats: { cycles: 780, uptimeHours: 270 },
  },
];
