import type { LogisticsModule } from '../types/logistics'

export const logisticsModules: LogisticsModule[] = [
  {
    id: 'input_station_1',
    name: 'Input Station',
    type: 'InputStation',
    position: { x: 70, y: 520 },
    stateTopic: 'logistics/input-station-1/state',
    metaTopic: 'logistics/input-station-1/meta',
  },
  {
    id: 'conv_entry_1',
    name: 'Entry Conveyor A',
    type: 'ConveyorLong',
    position: { x: 190, y: 520 },
    stateTopic: 'logistics/conv-entry-1/state',
  },
  {
    id: 'sensor_entry_1',
    name: 'Entry Sensor',
    type: 'BinarySensor',
    position: { x: 200, y: 485 },
    stateTopic: 'logistics/sensor-entry-1/state',
  },
  {
    id: 'conv_entry_2',
    name: 'Entry Conveyor B',
    type: 'ConveyorLong',
    position: { x: 400, y: 520 },
    stateTopic: 'logistics/conv-entry-2/state',
  },
  {
    id: 'sensor_entry_2',
    name: 'NFC Reader',
    type: 'NfcSensor',
    position: { x: 430, y: 485 },
    stateTopic: 'logistics/sensor-entry-2/state',
    metaTopic: 'logistics/sensor-entry-2/meta',
  },
  {
    id: 'conv_entry_3',
    name: 'Entry Conveyor C',
    type: 'ConveyorLong',
    position: { x: 610, y: 520 },
    stateTopic: 'logistics/conv-entry-3/state',
  },
  {
    id: 'turntable_entry',
    name: 'Turntable',
    type: 'ConveyorTurntable',
    position: { x: 800, y: 510 },
    stateTopic: 'logistics/turntable-entry/state',
  },
  {
    id: 'conv_exit',
    name: 'Exit Conveyor',
    type: 'ConveyorShort',
    position: { x: 940, y: 520 },
    stateTopic: 'logistics/conv-exit/state',
  },
  {
    id: 'sensor_exit',
    name: 'Exit Sensor',
    type: 'BinarySensor',
    position: { x: 955, y: 485 },
    stateTopic: 'logistics/sensor-exit/state',
  },
  {
    id: 'conv_main_1',
    name: 'Main Conveyor',
    type: 'ConveyorLong',
    position: { x: 230, y: 320 },
    stateTopic: 'logistics/conv-main-1/state',
  },
  {
    id: 'sensor_main_1',
    name: 'Main Line Sensor',
    type: 'BinarySensor',
    position: { x: 270, y: 285 },
    stateTopic: 'logistics/sensor-main-1/state',
  },
  {
    id: 'filling_unit_1',
    name: 'Pneumatic Filling',
    type: 'FillingUnit',
    position: { x: 440, y: 300 },
    stateTopic: 'logistics/filling-1/state',
    metaTopic: 'logistics/filling-1/meta',
  },
  {
    id: 'conv_main_2',
    name: 'Main Conveyor B',
    type: 'ConveyorLong',
    position: { x: 640, y: 320 },
    stateTopic: 'logistics/conv-main-2/state',
  },
  {
    id: 'sensor_main_2',
    name: 'Optical Sensor',
    type: 'BinarySensor',
    position: { x: 690, y: 285 },
    stateTopic: 'logistics/sensor-main-2/state',
  },
  {
    id: 'turntable_2',
    name: 'Turntable Junction',
    type: 'ConveyorTurntable',
    position: { x: 850, y: 300 },
    stateTopic: 'logistics/turntable-2/state',
  },
  {
    id: 'conv_short_2',
    name: 'Short Conveyor',
    type: 'ConveyorShort',
    position: { x: 980, y: 320 },
    stateTopic: 'logistics/conv-short-2/state',
  },
  {
    id: 'product_buffer',
    name: 'Product Buffer',
    type: 'ProductSensor',
    position: { x: 1080, y: 320 },
    stateTopic: 'logistics/product-buffer/state',
    metaTopic: 'logistics/product-buffer/meta',
  },
  {
    id: 'conv_to_lift',
    name: 'Conveyor to Lift',
    type: 'ConveyorShort',
    position: { x: 980, y: 200 },
    rotation: 90,
    stateTopic: 'logistics/conv-to-lift/state',
  },
  {
    id: 'lift_1',
    name: 'Lift',
    type: 'Lift',
    position: { x: 1020, y: 160 },
    stateTopic: 'logistics/lift-1/state',
    metaTopic: 'logistics/lift-1/meta',
  },
  {
    id: 'warehouse_col_1',
    name: 'High-Bay Column A',
    type: 'WarehouseColumn',
    position: { x: 1100, y: 140 },
    rotation: 90,
    stateTopic: 'logistics/warehouse-col-1/state',
  },
  {
    id: 'warehouse_col_2',
    name: 'High-Bay Column B',
    type: 'WarehouseColumn',
    position: { x: 1140, y: 140 },
    rotation: 90,
    stateTopic: 'logistics/warehouse-col-2/state',
  },
  {
    id: 'sensor_highbay',
    name: 'High-Bay Sensor',
    type: 'BinarySensor',
    position: { x: 1040, y: 240 },
    stateTopic: 'logistics/sensor-highbay/state',
  },
  {
    id: 'nfc_highbay',
    name: 'High-Bay NFC',
    type: 'NfcSensor',
    position: { x: 1065, y: 205 },
    stateTopic: 'logistics/nfc-highbay/state',
    metaTopic: 'logistics/nfc-highbay/meta',
  },
]
