import type { PlantComponent } from '../types/plant'

export const plantComponents: PlantComponent[] = [
  {
    id: 'assembly-station',
    name: 'Montage-Station',
    type: 'station',
    status: 'on',
    online: true,
    lastChanged: new Date().toISOString(),
    stats: { cycles: 245, uptimeHours: 1260 },
  },
  {
    id: 'conveyor-loop',
    name: 'Förderstrecke Nord',
    type: 'segment',
    status: 'on',
    online: true,
    lastChanged: new Date().toISOString(),
    stats: { cycles: 890, uptimeHours: 2320 },
  },
  {
    id: 'quality-gate',
    name: 'Qualitätsprüfung',
    type: 'station',
    status: 'off',
    online: true,
    lastChanged: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    stats: { cycles: 410, uptimeHours: 870 },
  },
  {
    id: 'packaging-cell',
    name: 'Verpackungszelle',
    type: 'station',
    status: 'on',
    online: true,
    lastChanged: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    stats: { cycles: 320, uptimeHours: 640 },
  },
  {
    id: 'warehouse-buffer',
    name: 'Pufferlager',
    type: 'segment',
    status: 'on',
    online: false,
    lastChanged: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    stats: { cycles: 120, uptimeHours: 420 },
  },
  {
    id: 'central-turntable',
    name: 'Drehtisch',
    type: 'actuator',
    status: 'on',
    online: true,
    lastChanged: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    stats: { cycles: 560, uptimeHours: 1100 },
  },
  {
    id: 'sensor-array',
    name: 'Sensor-Array',
    type: 'sensor',
    status: 'on',
    online: true,
    lastChanged: new Date(Date.now() - 1000 * 60 * 4).toISOString(),
    stats: { uptimeHours: 300 },
  },
  {
    id: 'pallet-lift',
    name: 'Hubwerk',
    type: 'actuator',
    status: 'off',
    online: false,
    lastChanged: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    stats: { cycles: 62, uptimeHours: 150 },
  },
  {
    id: 'loading-dock',
    name: 'Warenausgang',
    type: 'segment',
    status: 'on',
    online: true,
    lastChanged: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    stats: { cycles: 280, uptimeHours: 960 },
  },
  {
    id: 'rfid-gate',
    name: 'RFID-Station',
    type: 'sensor',
    status: 'on',
    online: true,
    lastChanged: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    stats: { cycles: 1020, uptimeHours: 1880 },
  },
]
